### ISSUE TITLE
Navigation bug

### ISSUE THREAD

**Issue by pizzaeater** [quickbirdstudios/XCoordinator-Example#2]
Fast login/logout taps cause a strange behaviour: sometimes a tabbar is invisible, sometimes I land directly to Recents page, sometimes to More page.

iOS 13.

Please test how it works.

**Comment by pauljohanneskraft** [comment]
This is expected behavior - Please take a look at AppCoordinator.prepareTransition for the code causing this behavior. We wanted to show as many different types of coordinators as possible in a rather simple app, even though this does not reflect common UX standards.

**Comment by pizzaeater** [comment]
Yeah, I just found it. Thanks for the explanation.

Maybe it's not so clear when somebody wants to see the use-case in the real app. The first impression — it's a bug.

**Comment by pauljohanneskraft** [comment]
I totally understand that, but to show all these kinds of coordinators, especially to have them use the same route type is not as easy in such a small app, so we decided to go with the current approach. We will definitely consider alternative approaches, if they can serve as a better example.

If you have a better approach or want to do other improvements to the example app, feel free to open additional issues to e.g. pitch an improvement idea or open a pull request to implement an idea.

**Comment by pizzaeater** [comment]
I understand the example app is too small to show everything. Thank you for your great work!
