### ISSUE TITLE
Crash in example app

### ISSUE THREAD

**Issue by d2vydov** [quickbirdstudios/XCoordinator-Example#5]
I tried to run example app and got a crash 
`XCoordinator-Example(15255,0x10ac88dc0) malloc: recording malloc and VM allocation stacks using lite mode`

there is an rx issue I guess, the call stack is 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/9073024/70316120-08979180-182c-11ea-9d0a-05b58241106a.png">

**Comment by pauljohanneskraft** [comment]
See https://github.com/quickbirdstudios/XCoordinator/issues/144 for more information. Since it should only be a temporary workaround to set `DEAD_CODE_STRIPPING` to `NO`, the Example app is not adapted accordingly. It should work fine once the issue is fixed in a future Xcode version.

**Comment by d2vydov** [comment]
that issue solved the problem, thank you.

so, I'll close this issue.
